import { noEmDash, sanitizeForExport } from "@/lib/sanitize";
import { standardLabel } from "@/lib/analysis/standards";

function esc(v: unknown) {
  return String(v ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] || c));
}

function scoreColor(score: number) {
  if (score >= 85) return "#166534";
  if (score >= 50) return "#92400e";
  return "#b91c1c";
}

export function buildGapJson(result: unknown) {
  return JSON.stringify(sanitizeForExport(result), null, 2);
}

export function buildGapReport(result: any, opts?: { auditor?: string; title?: string }) {
  const r = sanitizeForExport(result) as any;
  const auditor = opts?.auditor || "Silhouette LLC";
  const title = opts?.title || `${r.organization_name || "Organization"} - Incident Response Plan Gap Analysis`;
  const score = Number(r.compliance_score || 0);
  const color = scoreColor(score);
  const findings = Array.isArray(r.findings) ? r.findings : [];
  const phases = r.remediation_roadmap?.phases || [];
  const handling = r.data_handling || {};
  const controlBoard = r.control_board || {};
  const bucketScores = Object.values(r.bucket_scores || {}).map((bucket: any) => `<tr><td>${esc(bucket.label)}</td><td>${esc(bucket.points_earned)} / ${esc(bucket.points_possible)}</td><td>${esc(bucket.score)}%</td><td>${esc(bucket.controls_reviewed)}</td></tr>`).join("");
  const standardScores = Object.entries(r.score_breakdown || {}).map(([standard, value]: [string, any]) => `<tr><td>${esc(standardLabel(standard))}</td><td>${esc(value.score)}/100</td><td>${esc(value.controls_reviewed)}</td><td>${esc(value.controls_met)}</td><td>${esc(value.controls_partial)}</td><td>${esc(value.controls_failed)}</td></tr>`).join("");
  const rows = findings.map((f: any) => `<tr><td>${esc(f.capability || f.control_name || f.control_id)}</td><td>${esc(f.control_count || f.control_ids?.length || 1)}</td><td>${esc((f.standards || []).map((standard: string) => standardLabel(standard)).join(", "))}</td><td>${esc(f.status)}</td><td><strong style="color:${scoreColor(f.risk_level === "Critical" ? 0 : f.risk_level === "High" ? 40 : f.risk_level === "Medium" ? 65 : 90)}">${esc(f.risk_level)}</strong></td><td>${esc(f.finding)}</td></tr>`).join("");
  const controlRows = (Array.isArray(r.control_results) ? r.control_results : []).map((control: any) => `<tr><td>${esc(control.bucket_label)}</td><td>${esc(control.control_id)}</td><td>${esc((control.standards || []).map((standard: string) => standardLabel(standard)).join(", "))}</td><td>${esc(control.status)}</td><td>${esc(control.risk_level)}</td><td>${esc(control.requirement)}</td><td>${esc(control.evidence)}</td></tr>`).join("");
  const road = phases.map((p: any) => `<section class="phase"><h3>${esc(p.name)} <span>${esc(p.timeframe)}</span></h3>${(p.items || []).map((i: any) => `<p><b>${esc(i.title)}</b><br/>${esc(i.description)}<br/><small>${esc((i.references || []).join(", "))}</small></p>`).join("")}</section>`).join("");
  return noEmDash(`<!doctype html><html><head><meta charset="utf-8"/><title>${esc(title)}</title><style>
  @page{size:letter;margin:.55in}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#111;margin:0;background:#fff}.page{min-height:10in;page-break-after:always;padding:.45in}.cover{background:#110f1d;color:#fff;display:flex;flex-direction:column;justify-content:center}.brand{font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:#d2b8ff}.h1{font-family:Georgia,serif;font-size:42px;line-height:1.08;margin:18px 0}.rule{height:3px;width:4.5in;background:#9b6bff;margin:18px 0}.muted{color:#6b7280}.cover .muted{color:#d2b8ff}.score{width:104px;height:104px;border-radius:50%;display:flex;align-items:center;justify-content:center;border:10px solid ${color};font-size:34px;font-weight:700;color:${color};margin-right:24px}h2{font-family:Georgia,serif;font-size:24px;margin:0 0 16px;color:#9b6bff}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}th{text-align:left;color:#666;text-transform:uppercase;letter-spacing:.08em;border-bottom:2px solid #111;padding:7px;overflow-wrap:anywhere}td{border-bottom:1px solid #e5e7eb;padding:8px;vertical-align:top;overflow-wrap:anywhere}.phase{break-inside:avoid;page-break-inside:avoid;border-top:4px solid #9b6bff;padding:14px;border:1px solid #e5e7eb;margin-bottom:10px}.phase h3{font-family:Georgia,serif;margin:0 0 8px}.phase span{font:12px Arial;color:#777}.phase p{break-inside:avoid;page-break-inside:avoid}.footer{position:fixed;bottom:.25in;left:.55in;right:.55in;border-top:1px solid #ddd;padding-top:6px;font-size:9px;color:#888;display:flex;justify-content:space-between}@media print{button{display:none}}
  </style></head><body><div class="footer"><span>${esc(auditor)} | Compliance Gap Analysis</span><span>www.silhouettellc.com</span></div><section class="page cover"><div class="brand">${esc(auditor)}</div><div class="h1">${esc(title)}</div><div class="rule"></div><div class="muted">Confidential report | ${new Date().toLocaleDateString("en-US")}</div></section><section class="page"><h2>Executive Summary</h2><div style="display:flex;align-items:center;margin-bottom:22px"><div class="score">${score}</div><div><div class="brand" style="color:#888">Overall Compliance Score</div><h2 style="color:${color};margin-top:8px">${esc(r.overall_posture)}</h2><p class="muted">${esc(r.posture_summary)}</p></div></div><h2>Incident Response Capability Scores</h2><table><thead><tr><th>Capability</th><th>Points</th><th>Score</th><th>Controls</th></tr></thead><tbody>${bucketScores}</tbody></table><p class="muted">Fixed capability point budgets total 100. Control results within each capability determine the points earned.</p><h2>Standards Alignment</h2><table><thead><tr><th>Standard</th><th>Score</th><th>Reviewed</th><th>Met</th><th>Partial</th><th>Failed</th></tr></thead><tbody>${standardScores}</tbody></table><p class="muted">Standards alignment scores provide traceability and are not averaged again into the overall score.</p><h2>Assessment Basis</h2><p><b>Control boards:</b> ${esc(controlBoard.citation || "Not recorded")}</p><p><b>Scoring:</b> ${esc(r.scoring_method || "Control-level scoring method not recorded")}</p><h2>Data Handling</h2><p><b>Uploader attestation:</b> ${esc(handling.message || "No uploader data-handling attestation was recorded for this assessment.")}</p><p class="muted">This advisory disclosure does not affect the control-based compliance score.</p></section><section class="page"><h2>Consolidated Remediation Findings</h2><table><thead><tr><th>Capability</th><th>Controls</th><th>Standards</th><th>Status</th><th>Risk</th><th>Finding</th></tr></thead><tbody>${rows}</tbody></table></section><section class="page"><h2>Priority Remediation Roadmap</h2>${road}<h2>Conclusion & Limitations</h2><p>This assessment covers submitted documentation only. Operational controls and configurations not captured in reviewed artifacts are outside scope. Findings should be reviewed with compliance counsel before regulatory submission.</p></section>${controlRows ? `<section class="page"><h2>Control Traceability Appendix</h2><table><thead><tr><th>Capability</th><th>Control</th><th>Standard</th><th>Status</th><th>Priority</th><th>Requirement</th><th>Evidence</th></tr></thead><tbody>${controlRows}</tbody></table></section>` : ""}</body></html>`);
}

export function buildGapDeck(result: any) {
  const r = sanitizeForExport(result) as any;
  const findings = Array.isArray(r.findings) ? r.findings.slice(0, 8) : [];
  const standardScores = Object.entries(r.score_breakdown || {}).map(([standard, value]: [string, any]) => `<li><b>${esc(standardLabel(standard))}</b>: ${esc(value.score)}/100</li>`).join("");
  const bucketScores = Object.values(r.bucket_scores || {}).map((bucket: any) => `<li><b>${esc(bucket.label)}</b>: ${esc(bucket.points_earned)} of ${esc(bucket.points_possible)} points</li>`).join("");
  const roadmapSlides = (r.remediation_roadmap?.phases || []).map((phase: any) => `<section class="slide"><div class="k">Remediation Roadmap</div><h1>${esc(phase.name)} <small>${esc(phase.timeframe)}</small></h1><ol>${(phase.items || []).map((item: any) => `<li><b>${esc(item.title)}</b><br/><span>${esc(item.description)}</span></li>`).join("")}</ol></section>`).join("");
  return noEmDash(`<!doctype html><html><head><meta charset="utf-8"/><title>${esc(r.organization_name)} Deck</title><style>body{margin:0;font-family:Arial,sans-serif}.slide{min-height:100vh;page-break-after:always;padding:8vh 9vw;display:flex;flex-direction:column;justify-content:center}.dark{background:#110f1d;color:#fff}.k{letter-spacing:.24em;text-transform:uppercase;color:#9b6bff;font-size:12px}.dark .k{color:#d2b8ff}.title{font-family:Georgia,serif;font-size:54px;line-height:1.05}.score{font-size:110px;font-weight:700;color:${scoreColor(Number(r.compliance_score || 0))}}h1 small{color:#6b7280;font:16px Arial,sans-serif}li{font-size:20px;margin:10px 0;color:#333}li span{font-size:16px;color:#6b7280}.dark li{color:#d2b8ff}</style></head><body><section class="slide dark"><div class="k">Silhouette LLC</div><div class="title">${esc(r.organization_name)}</div><p>Incident Response Plan Gap Analysis</p></section><section class="slide"><div class="k">Executive Summary</div><div class="score">${esc(r.compliance_score)}</div><h1>${esc(r.overall_posture)}</h1><p>${esc(r.posture_summary)}</p></section><section class="slide"><div class="k">Incident Response Capabilities</div><ul>${bucketScores}</ul><p>Fixed capability point budgets total 100.</p></section><section class="slide"><div class="k">Standards Alignment</div><ul>${standardScores}</ul><p>Alignment scores provide traceability and are not averaged again into the overall score.</p></section><section class="slide"><div class="k">Key Findings</div><ul>${findings.map((f: any) => `<li><b>${esc(f.risk_level)}</b> - ${esc(f.finding)}</li>`).join("")}</ul></section>${roadmapSlides}<section class="slide dark"><div class="k">Next Steps</div><div class="title">Remediate, test, reassess.</div></section></body></html>`);
}

export function buildNetworkGapJson(result: unknown) {
  return JSON.stringify(sanitizeForExport(result), null, 2);
}

export function buildNetworkGapReport(result: any) {
  const r = sanitizeForExport(result) as any;
  const organizations = Array.isArray(r.organizations) ? r.organizations : [];
  const gaps = Array.isArray(r.common_gaps) ? r.common_gaps : [];
  const score = Number(r.compliance_score || 0);
  const organizationRows = organizations.map((organization: any) => `<tr><td>${esc(organization.organization_name)}</td><td>${esc(organization.overall_posture)}</td><td>${esc(organization.compliance_score)}/100</td>${Object.keys(r.score_breakdown || {}).map((standard) => `<td>${esc(organization.score_breakdown?.[standard]?.score ?? "-")}</td>`).join("")}</tr>`).join("");
  const gapRows = gaps.map((gap: any) => `<tr><td>${esc(gap.control_id)}</td><td>${esc(gap.risk_level)}</td><td>${esc(gap.requirement || gap.control_name)}</td><td>${esc((gap.affected_organizations || []).join(", "))}</td><td>${esc(gap.affected_count)}/${organizations.length}</td></tr>`).join("");
  const capabilities = Object.values(r.bucket_scores || {}).map((value: any) => `<div class="metric"><span>${esc(value.label)}</span><b>${esc(value.points_earned)} / ${esc(value.points_possible)}</b><small>${esc(value.organizations_reviewed)} organizations | ${esc(value.score)}%</small></div>`).join("");
  return noEmDash(`<!doctype html><html><head><meta charset="utf-8"/><title>${esc(r.network_name)} Network IRP Gap Analysis</title><style>
  @page{size:letter landscape;margin:.45in}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#16131e;margin:0;background:#fff}.page{min-height:7.55in;page-break-after:always;padding:.35in}.cover{background:#110f1d;color:#fff;display:flex;flex-direction:column;justify-content:center}.brand{font-size:12px;letter-spacing:.24em;text-transform:uppercase;color:#d2b8ff}.h1{font-family:Georgia,serif;font-size:40px;line-height:1.08;margin:18px 0}.rule{height:3px;width:4.5in;background:#9b6bff;margin:18px 0}.muted{color:#6b7280}.cover .muted{color:#d2b8ff}h2{font-family:Georgia,serif;font-size:24px;margin:0 0 16px;color:#7142c7}.score{font-size:64px;color:${scoreColor(score)};font-weight:700}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metric{display:grid;gap:5px;padding:14px;border:1px solid #ddd;border-radius:6px}.metric span{font-size:10px;color:#666}.metric b{font-size:22px}.metric small{color:#777}table{width:100%;border-collapse:collapse;font-size:10px;table-layout:fixed}th{text-align:left;color:#666;text-transform:uppercase;letter-spacing:.06em;border-bottom:2px solid #111;padding:7px}td{border-bottom:1px solid #e5e7eb;padding:7px;vertical-align:top;overflow-wrap:anywhere}.footer{position:fixed;bottom:.18in;left:.45in;right:.45in;border-top:1px solid #ddd;padding-top:5px;font-size:8px;color:#888;display:flex;justify-content:space-between}
  </style></head><body><div class="footer"><span>Silhouette LLC | Network IRP Gap Analysis</span><span>www.silhouettellc.com</span></div><section class="page cover"><div class="brand">Silhouette LLC</div><div class="h1">${esc(r.network_name)}<br/>Network Incident Response Plan Gap Analysis</div><div class="rule"></div><div class="muted">${organizations.length} organization reports | Confidential | ${new Date().toLocaleDateString("en-US")}</div></section><section class="page"><h2>Network Executive Summary</h2><div class="score">${score}/100</div><h3>${esc(r.overall_posture)}</h3><p>${esc(r.posture_summary)}</p><h2>Capability Averages</h2><div class="metrics">${capabilities}</div><h2>Organization Comparison</h2><table><thead><tr><th>Organization</th><th>Posture</th><th>Score</th>${Object.keys(r.score_breakdown || {}).map((standard) => `<th>${esc(standardLabel(standard))}</th>`).join("")}</tr></thead><tbody>${organizationRows}</tbody></table></section><section class="page"><h2>Common Capability Gaps</h2><p class="muted">Ranked by the number of organizations affected, then by priority.</p><table><thead><tr><th>Capability</th><th>Priority</th><th>Requirement</th><th>Organizations affected</th><th>Coverage</th></tr></thead><tbody>${gapRows}</tbody></table></section></body></html>`);
}

export function buildNetworkGapDeck(result: any) {
  const r = sanitizeForExport(result) as any;
  const organizations = Array.isArray(r.organizations) ? r.organizations : [];
  const priorities = Array.isArray(r.network_priorities) ? r.network_priorities.slice(0, 8) : [];
  return noEmDash(`<!doctype html><html><head><meta charset="utf-8"/><title>${esc(r.network_name)} Network Deck</title><style>body{margin:0;font-family:Arial,sans-serif}.slide{min-height:100vh;page-break-after:always;padding:8vh 8vw;display:flex;flex-direction:column;justify-content:center}.dark{background:#110f1d;color:#fff}.k{letter-spacing:.24em;text-transform:uppercase;color:#9b6bff;font-size:12px}.dark .k{color:#d2b8ff}.title{font-family:Georgia,serif;font-size:52px;line-height:1.08}.score{font-size:105px;font-weight:700;color:${scoreColor(Number(r.compliance_score || 0))}}table{width:100%;border-collapse:collapse;font-size:20px}td,th{padding:12px;border-bottom:1px solid #ddd;text-align:left}li{font-size:20px;margin:13px 0}</style></head><body><section class="slide dark"><div class="k">Silhouette LLC</div><div class="title">${esc(r.network_name)}</div><p>Network Incident Response Plan Gap Analysis | ${organizations.length} organizations</p></section><section class="slide"><div class="k">Network posture</div><div class="score">${esc(r.compliance_score)}</div><h1>${esc(r.overall_posture)}</h1><p>${esc(r.posture_summary)}</p></section><section class="slide"><div class="k">Organization comparison</div><table><thead><tr><th>Organization</th><th>Posture</th><th>Score</th></tr></thead><tbody>${organizations.map((organization: any) => `<tr><td>${esc(organization.organization_name)}</td><td>${esc(organization.overall_posture)}</td><td>${esc(organization.compliance_score)}/100</td></tr>`).join("")}</tbody></table></section><section class="slide"><div class="k">Network priorities</div><ul>${priorities.map((priority: any) => `<li><b>${esc(priority.risk_level)} | ${esc(priority.control_id)}</b><br/>${esc(priority.control_name)} | ${esc(priority.affected_count)}/${organizations.length} organizations affected</li>`).join("")}</ul></section><section class="slide dark"><div class="k">Next steps</div><div class="title">Coordinate remediation, validate locally, reassess together.</div></section></body></html>`);
}
